name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      BUILD_VERSION:
        description: 'Version number for the build'
        required: true
        default: '1.0.0'
      REBUILD:
        description: 'Rebuild code'
        required: true
        default: 'false'
        type: boolean

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Install Java, Maven, Zip, Curl
        run: |
          echo "Checking system dependencies..."
          sudo apt update
          sudo apt install -y openjdk-17-jdk maven zip curl

      - name: Verify Installed Versions
        run: |
          java -version
          mvn -version
          zip --version
          curl --version

  build:
    runs-on: ubuntu-latest
    needs: setup-environment
    if: ${{ github.event.inputs.REBUILD == 'true' || github.event.inputs.REBUILD == true }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package -Dversion=${{ github.event.inputs.BUILD_VERSION }}

      - name: Zip the Build using ZIP
        run: |
          zip -r develop-${{ github.event.inputs.BUILD_VERSION }}.zip target/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-zip
          path: develop-${{ github.event.inputs.BUILD_VERSION }}.zip
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write  # Cần quyền ghi để tạo release
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-zip

      - name: Create GitHub Release (if not exists)
        run: |
          TAG="v${{ github.event.inputs.BUILD_VERSION }}"
          RELEASE_NAME="Release ${{ github.event.inputs.BUILD_VERSION }}"
          
          # Kiểm tra xem release đã tồn tại chưa
          if gh release view "$TAG" > /dev/null 2>&1; then
            echo "Release $TAG already exists. Skipping creation."
          else
            echo "Creating new release: $TAG"
            gh release create "$TAG" develop-${{ github.event.inputs.BUILD_VERSION }}.zip --title "$RELEASE_NAME" --notes "Automated release for version ${{ github.event.inputs.BUILD_VERSION }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload Build to Release
        run: |
          TAG="v${{ github.event.inputs.BUILD_VERSION }}"
          gh release upload "$TAG" develop-${{ github.event.inputs.BUILD_VERSION }}.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
